' TUTORIAL 1

' CLS [It is used to clear the screen]
' PRINT [It is used to show text in the screen]
' INPUT [It is used to ask the user for some information]
' VARIABLES name$, age

CLS
PRINT "Hello! My name is Fernando. What is your name."
INPUT "Write your name: ", name$

PRINT
PRINT "So, your name is "; name$
PRINT "Nice to meet you!"

PRINT
PRINT "What is your age, how old are you..."
INPUT "Input your age please: ", age

PRINT
PRINT "So, you are "; age; " years old!"

PRINT
PRINT "Your name is "; name$; " and you are "; age; " years old! Nice!"



